title: Goodbuu's performance hacking
description: "A blog about C++."
author:
  name: "Goodbuu"
  email: "goodbuu@qq.com"
  url: "https://goodbuu.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom variables
owner : "Goodbuu"
year : "2025"
